### ISSUE TITLE
NoSuchMethodException occurred in Spigot latest 1.21.1

### ISSUE THREAD

**Issue by snowpegeon** [saicone/rtag#9]
Hi.
This is the current latest build of Spigot.
CraftBukkit version 4312-Spigot-a759b62-0fb24bb (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

Currently, when loading Rtag1.5.6, NoSuchMethodException occurs when loading.
For the time being, I have confirmed that there are no problems with my plugin, so it is a low priority, but I would appreciate your investigation.

I am using translation software, so please ask if you have any problems.

ErrorLog

[16:54:30] [Server thread/INFO]: [Rtag] Loading Rtag v1.5.6
[16:54:30] [Server thread/WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_21_R1.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)
[16:54:30] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
[16:54:30] [Server thread/WARN]:        at com.saicone.rtag.util.EasyLookup.unreflectMethod(EasyLookup.java:510)
[16:54:30] [Server thread/WARN]:        at com.saicone.rtag.util.SkullTexture.<clinit>(SkullTexture.java:74)
[16:54:30] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[16:54:30] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:421)
[16:54:30] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:412)
[16:54:30] [Server thread/WARN]:        at com.saicone.rtag.RtagPlugin.loadRtagClass(RtagPlugin.java:44)
[16:54:30] [Server thread/WARN]:        at com.saicone.rtag.RtagPlugin.onLoad(RtagPlugin.java:18)
[16:54:30] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:469)
[16:54:30] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236)
[16:54:30] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
[16:54:30] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[16:54:30] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Rubenicos** [comment]
Use the latest version
